source 'https://rubygems.org'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'slim'
gem 'rake'
gem 'rerun'
gem 'tilt', '1.4.1'
gem 'thin'
gem 'faye'
gem 'rack'
gem 'tilt', '1.4.1'
gem 'async_sinatra'
